#pragma once

#define MAIN_USE_DEBUG_UI 0
#define MAIN_USE_JAVA_UI 0
#define MAIN_USE_BASIC_FULL_AI_EVO 0
#define MAIN_USE_REINFORCEMENT_BASIC_EVO 0
#define MAIN_USE_SIMPLE_NET_REINFORCE 0
#define MAIN_USE_LEAGUE_PLAY 1
